name: Build

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run npm clean-install
      run: npm clean-install
    - name: Run build
      run: npm run build
    - name: Commit build
      if: matrix.node-version == '14.x'
      run: |
        git config --global user.name 'cffinit GitHub Action'
        git config --global user.email 'cffinit@users.noreply.github.com'
        git commit -am "Automated build update"
        git push

