name: Publish

on: # publish when main branch changes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Run npm clean-install
      run: npm clean-install
    - name: Run build
      run: npm run build
    - name: Update docs folder
      run: |
        git config --global user.name 'cffinit'
        git config --global user.email 'cffinit@users.noreply.github.com'
        git add docs/
        git commit -m "Update github.io page"
        git push


